apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    path: argocd/base/traefik
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Service
      name: traefik
      jqPathExpressions:
      - .metadata.labels."app.kubernetes.io/instance"
      - .metadata.labels."helm.sh/chart"
  revisionHistoryLimit: 2