apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - PruneLast=true
  revisionHistoryLimit: 2