service:
  dns-tcp:
    enabled: false
  dns-udp:
    enabled: false


persistence:
  config:
    enabled: true
    retain: true
    mountPath: /opt/adguardhome/conf
  data:
    enabled: true
    retain: true
    mountPath: /opt/adguardhome/work


probes:
  liveness:
    enabled: false
  rediness:
    enabled: false
  startup:
    enabled: false