service:
  main:
    ports:
      http:
        port: 80
  dns-tcp:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/allow-shared-ip: adguard-home
    ports:
      dns-tcp:
        enabled: true
        port: 53
      dns-over-tls:
        enabled: true
        port: 853
  dns-udp:
    enabled: true
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/allow-shared-ip: adguard-home
    ports:
      dns-udp:
        enabled: true
        protocol: UDP
        port: 53
      dns-over-quic:
        enabled: true
        protocol: UDP
        port: 784


persistence:
  config:
    enabled: true
    retain: true
    mountPath: /opt/adguardhome/conf
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 1Gi
  data:
    enabled: true
    retain: true
    mountPath: /opt/adguardhome/work
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 1Gi


probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false