apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-{{ .Values.name }}
spec:
  secretName: ext-cert-{{ .Values.name }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ .Values.clusterIssuer }}
  commonName: {{ .Values.name }}.bowmans.site
  dnsNames:
    - {{ .Values.name }}.bowmans.site