apiVersion: v1
kind: Service
metadata:
  name: ext-svc-{{ .Values.name | replace "." "-" }}
spec:
  type: ExternalName
  externalName: {{ .Values.externalName }}
  ports:
    - port: {{ .Values.port }}