fullnameOverride: tempo
minio:
  enabled: false
metaMonitoring:
  serviceMonitor:
    enabled: false
  grafanaAgent:
    enabled: false
gateway:
  enabled: true
metricsGenerator:
  enabled: true
  config:
    storage:
      remote_write:
      - url: http://vmsingle-vmstack.victoria-metrics:8429/api/v1/write
traces:
  jaeger:
    grpc:
      enabled: true
    thriftCompact:
      enabled: true
    thriftBinary:
      enabled: true
    thriftHttp: 
      enabled: true  
  otlp:
    http: 
      enabled: true
    grpc: 
      enabled: true
global:
  dnsService: "kube-dns"