global:
  dnsService: "kube-dns"
  dnsNamespace: "kube-system"
  clusterDomain: "cluster.local."
fullnameOverride: tempo
minio:
  enabled: false
tempo:
  structuredConfig:
    query_frontend:
      search:
        max_duration: '0'
metaMonitoring:
  serviceMonitor:
    enabled: false
  grafanaAgent:
    enabled: false
    installOperator: false
persistence:
  enabled: false
gateway:
  enabled: true
ingester:
  persistence:
    enabled: false
    size: 5Gi
compactor:
  config: 
    compaction:
      block_retention: 336h
metricsGenerator:
  enabled: true
  config: 
    storage:
      remote_write:
      - url: http://vmsingle-vmstack.victoria-metrics:8429/api/v1/write
traces:
  jaeger:
    grpc:
      enabled: true
    thriftCompact:
      enabled: true
    thriftBinary:
      enabled: true
    thriftHttp: 
      enabled: true  
  otlp:
    http: 
      enabled: true
    grpc: 
      enabled: true