apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: requestrr-k8s-keda
spec:
  scaleTargetRef:
    name: requestrr-k8s
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"