apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whoami-certificate
spec:
  secretName: whoami-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: whoami.homelab.bowmans.site
  dnsNames:
    - whoami.homelab.bowmans.site