apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: grafana-agent-flow
  name: grafana-agent-flow
  namespace: monitoring
spec:
  ports:
    - name: http-metrics
      port: 80
      protocol: TCP
      targetPort: 12345
    - name: grpc-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: http-otlp
      port: 4318
      protocol: TCP
      targetPort: 4318
  selector:
    app.kubernetes.io/instance: grafana-alloy
    app.kubernetes.io/name: alloy