apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-role-binding
subjects:
- kind: ServiceAccount
  name: secrets-store-csi-driver
  namespace: csi-secrets-store
roleRef:
  kind: ClusterRole
  name: secret-role
  apiGroup: rbac.authorization.k8s.io