apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: netbox-certificate
spec:
  secretName: netbox-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: netbox.homelab.bowmans.site
  dnsNames:
    - netbox.homelab.bowmans.site