apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controller
  namespace: argocd
spec:
  project: default
  source:
    chart: actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    repoURL: ghcr.io
    targetRevision: 0.8.2
    helm:
      values: |
        githubConfigUrl: ""
        githubConfigSecret: pre-defined-secret
        template:
          spec:
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                command: ["/home/runner/run.sh"]
controllerServiceAccount:
  namespace: github-arc
  name:  controller-gha-rs-controller
  destination:
    server: "https://kubernetes.default.svc"
    namespace: github-arc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true