githubConfigUrl: ""
githubConfigSecret: pre-defined-secret
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
controllerServiceAccount:
  namespace: github-arc
  name:  controller-gha-rs-controller