apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homer-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homer.homelab.bowmans.site`)
      kind: Rule
      services:
      - name: homer
        port: 8080
      middlewares:
      - name: private-ips-allow
        namespace: traefik
  tls:
    secretName: homer-certificate