apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: homer-keda
  namespace: default
spec:
  scaleTargetRef:
    name: homer
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 3
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"