apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: homer-vpa
spec:
  targetRef:
    name: homer
    kind: Deployment
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      mode: "Auto"
      controlledResources:
      - memory