datasources:
  datasources.yaml:
    apiVersino: 1
    datasources:
    - name: loki
      type: loki
      url: http://loki-gateway.loki:80
      jsonData:
        derivedFields:
          - datasourceUid: Tempo
            matcherRegex: '"[tT]race(?:.?)[iI][dD]":\s?"(.\w+)"'
            name: TraceID
            url: "$${__value.raw}"
    - name: Tempo
      type: tempo
      url: http://tempo.tempo:3100
      access: proxy
      basicAuth: false
admin:
  existingSecret: "grafana-admin-details"
  userKey: admin-user
  passwordKey: admin-password