datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      uid: loki
      url: http://loki-gateway.loki:80
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: '"[tT]race(?:.?)[iI][dD]":\s?"(.\w+)"'
            name: TraceID
            url: "$${__value.raw}"
    - name: tempo
      type: tempo
      uid: tempo
      url: http://tempo-gateway.tempo:80
      access: proxy
      basicAuth: false
      jsonData:
        tracesToLogs:
          datasourceUid: 'loki'
          tags: ['job', 'instance', 'pod', 'namespace']
          mappedTags: [{ key: 'service.name', value: 'ServiceName' }]
          mapTagNamesEnabled: false
          filterByTraceID: false
          filterBySpanID: false
        tracesToMetrics:
          datasourceUid: 'victoria-metrics'
        serviceMap:
          datasourceUid: 'victoria-metrics'
        nodeGraph:
          enabled: true
        lokiSearch:
          datasourceUid: 'loki'
    - name: prometheus
      type: prometheus
      url: "http://vmsingle-vmstack.victoria-metrics:8429"
      access: proxy
      isDefault: true
      jsonData: 
        {}
admin:
  existingSecret: "grafana-admin-details"
  userKey: admin-user
  passwordKey: admin-password
downloadDashboardsImage:
  registry:   docker.io
  repository: highcanfly/net-tools
  tag: latest
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    14584-argocd:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/14584-argocd.json
      token: ''
    14981-coredns:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/14981-coredns.json
      token: ''
    18283-kubernetes-dashboard:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/18283-kubernetes-dashboard.json
      token: ''
    1860-node-exporter-full:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/1860-node-exporter-full.json
      token: ''
    6417-kubernetes-cluster-prometheus:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/6417-kubernetes-cluster-prometheus.json
      token: ''