extraVolumeMounts:
- name: 'secrets'
  mountPath: '/mnt/secrets-store'
  readOnly: true
extraVolumes:
- name: secrets
  csi:
    driver: 'secrets-store.csi.k8s.io'
    readOnly: true
    volumeAttributes:
      secretProviderClass: 'gafana-spc'
envFromSecrets:
- name: github-oauth
grafana.ini:
  server:
    root_url: "https://grafana.homelab.bowmans.site"
  auth.github:
    enabled: true
    allow_sign_up: true
    scopes: user:email,read:org
    auth_url: https://github.com/login/oauth/authorize
    token_url: https://github.com/login/oauth/access_token
    api_url: https://api.github.com/user
    client_id: "${client_id}"
    client_secret: "${client_secret}"
    team_ids:
      - 10178744
    allowed_organizations:
      - "sam-bowman-org"
    allow_assign_grafana_admin: true
    role_attribute_path: "contains(groups[*], '@sam-bowman-org/main') && 'GrafanaAdmin' || 'Viewer'"
    allowed_domains: "bowmans.site homelab.bowmans.site grafana.homelab.bowmans.site"
revisionHistoryLimit: 2
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      uid: loki
      url: http://loki-gateway.loki:80
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: '"[tT]race(?:.?)[iI][dD]":\s?"(.\w+)"'
            name: TraceID
            url: "$${__value.raw}"
    - name: tempo
      type: tempo
      uid: tempo
      url: http://tempo-gateway.tempo:80
      access: proxy
      basicAuth: false
      jsonData:
        tracesToLogs:
          datasourceUid: 'loki'
          tags: ['job', 'instance', 'pod', 'namespace']
          mappedTags: [{ key: 'service.name', value: 'ServiceName' }]
          mapTagNamesEnabled: false
          filterByTraceID: false
          filterBySpanID: false
        tracesToMetrics:
          datasourceUid: 'victoria-metrics'
        serviceMap:
          datasourceUid: 'victoria-metrics'
        nodeGraph:
          enabled: true
        lokiSearch:
          datasourceUid: 'loki'
    - name: prometheus
      type: prometheus
      url: "http://vmsingle-vmstack.victoria-metrics:8429"
      access: proxy
      isDefault: true
      jsonData: 
        {}
admin:
  existingSecret: "grafana-admin-details"
  userKey: admin-user
  passwordKey: admin-password
downloadDashboardsImage:
  registry:   docker.io
  repository: highcanfly/net-tools
  tag: latest
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    1860-node-exporter-full:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/1860-node-exporter-full.json
      token: ''
    18814-kubernetes-networking-clusters:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/18814-kubernetes-networking-clusters.json
      token: ''
    20330-kubernetes-etcd:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/20330-kubernetes-etcd.json
      token: ''
    20331-kubernetes-api-server:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/20331-kubernetes-api-server.json
      token: ''
    20925-kubernetes-networking-dns-cluster:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/20925-kubernetes-networking-dns-cluster.json
      token: ''
    20926-kubernetes-networking-dns-workload:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/20926-kubernetes-networking-dns-workload.json
      token: ''
    20927-kubernetes-networking-drops-workload:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/20927-kubernetes-networking-drops-workload.json
      token: ''
    20928-kubernetes-networking-pod-flows-namespace:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/20928-kubernetes-networking-pod-flows-namespace.json
      token: ''
    20929-kubernetes-networking-pod-flows-workload:
      url: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/monitoring/grafana/dashboards/20929-kubernetes-networking-pod-flows-workload.json
      token: ''