datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      url: http://loki-gateway.loki:80
      jsonData:
        derivedFields:
          - datasourceUid: Tempo
            matcherRegex: '"[tT]race(?:.?)[iI][dD]":\s?"(.\w+)"'
            name: TraceID
            url: "$${__value.raw}"
    - name: tempo
      type: tempo
      url: http://tempo.tempo:3100
      access: proxy
      basicAuth: false
    - name: victoria-metrics
      type: prometheus
      url: "http://vmsingle-victoria-metrics-victoria-metrics-k8s-stack.victoria-metrics:8429"
      access: proxy
admin:
  existingSecret: "grafana-admin-details"
  userKey: admin-user
  passwordKey: admin-password
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
   default:
     node-exporter-full:
       url: https://grafana.com./api/dashboards/1860/revisions/36/download
       datasource: victoria-metrics