datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      uid: loki
      url: http://loki-gateway.loki:80
      jsonData:
        derivedFields:
          - datasourceUid: tempo
            matcherRegex: '"[tT]race(?:.?)[iI][dD]":\s?"(.\w+)"'
            name: TraceID
            url: "$${__value.raw}"
    - name: tempo
      type: tempo
      uid: tempo
      url: http://tempo-gateway.tempo:80
      access: proxy
      basicAuth: false
      jsonData:
        tracesToLogs:
          datasourceUid: 'loki'
          tags: ['job', 'instance', 'pod', 'namespace']
          mappedTags: [{ key: 'service.name', value: 'ServiceName' }]
          mapTagNamesEnabled: false
          filterByTraceID: false
          filterBySpanID: false
        tracesToMetrics:
          datasourceUid: 'victoria-metrics'
        serviceMap:
          datasourceUid: 'victoria-metrics'
        nodeGraph:
          enabled: true
        lokiSearch:
          datasourceUid: 'loki'
    - name: victoria-metrics
      type: prometheus
      url: "http://vmsingle-vmstack.victoria-metrics:8429"
      access: proxy
      isDefault: true
      jsonData: 
        {}
admin:
  existingSecret: "grafana-admin-details"
  userKey: admin-user
  passwordKey: admin-password
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
   default:
     node-exporter-full:
       url: https://grafana.com./api/dashboards/1860/revisions/36/download
       datasource: victoria-metrics