coder:
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-db-url
          key: url
    - name: CODER_ACCESS_URL
      value: "https://coder.bowmans.site"
    - name: CODER_WILDCARD_ACCESS_URL
      value: "*.coder.bowmans.site"
  service:
    type: ClusterIP