additionalVolumeMounts:
  - name: 'github-arc-secrets'
    mountPath: '/mnt/secrets-store'
    readOnly: true
additionalVolumes:
  - name: 'github-arc-secrets'
    csi:
      driver: 'secrets-store.csi.k8s.io'
      readOnly: true
      volumeAttributes:
        secretProviderClass: 'github-arc-spc'
githubConfigSecret: github-client-secret