env:
- name: GITHUB_TOKEN_FROM_SECRET
  valueFrom:
    secretKeyRef:
      name: github-client-secret
      key: client-secret
additionalVolumeMounts:
  - name: 'secrets'
    mountPath: '/mnt/secrets-store'
    readOnly: true
additionalVolumes:
  - name: secrets
    csi:
      driver: 'secrets-store.csi.k8s.io'
      readOnly: true
      volumeAttributes:
        secretProviderClass: 'github-arc-spc'