# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: sonarr
#   labels:
#     app: sonarr
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: sonarr
#   template:
#     metadata:
#       labels:
#         app: sonarr
#     spec:
#       volumes:
#       - name: sonarr-config-pvc
#         persistentVolumeClaim:
#           claimName: sonarr-config-pvc
#       - name: sonarr-tv-pvc
#         persistentVolumeClaim:
#           claimName: sonarr-tv-pvc
#       - name: sonarr-downloads-pvc
#         persistentVolumeClaim:
#           claimName: sonarr-downloads-pvc
#       containers:
#       - name: sonarr
#         image: lscr.io/linuxserver/sonarr:latest
#         ports:
#         - containerPort: 8989
#         env:
#         - name: PUID
#           value: "1000"
#         - name: PGID
#           value: "1000"
#         - name: TZ
#           value: "Europe/London"
#         volumeMounts:
#         - mountPath: /config
#           name: sonarr-config-pvc
#         - mountPath: /tv
#           name: sonarr-tv-pvc
#         - mountPath: /downloads
#           name: sonarr-downloads-pvc