apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.10.20.50
    path: "/mnt/app-pool/apps/sonarr"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv-pv
spec:
  storageClassName: ""
  # capacity:
  #   storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.10.20.50
    path: "/mnt/pool/media/tv"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads-pv
spec:
  storageClassName: ""
  # capacity:
  #   storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.10.20.50
    path: "/mnt/pool/media/downloads"
    readOnly: false