apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-pvc
spec:
  storageClassName: "" 
  volumeName: sonarr-config-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-tv-pvc
spec:
  storageClassName: "" 
  volumeName: sonarr-tv-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-downloads-pvc
spec:
  storageClassName: "" 
  volumeName: sonarr-downloads-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem