{{- if eq $.Values.cert.enabled true }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ $.Values.name }}-certificate"
spec:
  secretName: "{{ $.Values.name }}-certificate"
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: "{{ coalesce $.Values.ingress.hostOverride $.Values.name }}-homelab.bowmans.site"
  dnsNames:
    - "{{ coalesce $.Values.ingress.hostOverride $.Values.name }}-homelab.bowmans.site"
{{- end }}