{{- if eq $.Values.cert.enabled true }}
{{- $host := $.Values.name -}}
{{- if $.Values.ingress.hostOverride }}
{{- $host := $.Values.ingress.hostOverride -}}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.name }}-certificate
spec:
  secretName: {{ $.Values.name }}-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: {{ $host }}.homelab.bowmans.site
  dnsNames:
    - {{ $host }}.homelab.bowmans.site
{{- end }}