apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.name }}-deployment
  labels:
    app: {{ $.Values.name }}
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ $.Values.name }}
  template:
    metadata:
      labels:
        app: {{ $.Values.name }}
    spec:
      containers:
      {{- range $.Values.containers }}
      - name: {{ .name }}
        image:  {{ .image }}
        {{- if .command }}
        command: {{ .command }}
        {{- end }}
        ports:
        {{- range .ports }}
        - containerPort: {{ .port }}
        {{- end }}
        volumeMounts:
        {{- range $.Values.volumes }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}
          readOnly: false
        {{- end }}
        env:
        {{- range .env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
        {{- end }}
      {{- end }}
      volumes:
      {{- range $.Values.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ $.Values.name }}-pvc
      {{- end }}
      dnsConfig:
        nameservers:
          - 8.8.8.8
        searches:
          - api.github.com
          - api.themoviedb.org
          - plex.tv
        options:
          - name: ndots
            value: "1"