{{- if eq $.Values.ingress.enabled true }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Values.name }}-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ coalesce $.Values.ingress.hostOverride $.Values.name }}-homelab.bowmans.site`)
      kind: Rule
      services:
      {{- range $.Values.containers }}
      {{- range .ports }}
      - name: {{ $.Values.name }}-service
        port: {{ .port }}
      {{- end }}
      {{- end }}
  tls:
    secretName: {{ $.Values.name }}-certificate
{{- end }}