{{- if eq $.Values.ingress.enabled true }}
{{- $host := $.Values.name -}}
{{- if $.Values.ingress.hostOverride }}
{{- $host := $.Values.ingress.hostOverride -}}
{{- end }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Values.name }}-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ $host }}.homelab.bowmans.site`)
      kind: Rule
      services:
      {{- range $.Values.containers }}
      {{- range .ports }}
      - name: {{ $.Values.name }}-service
        port: {{ . }}
      {{- end }}
      {{- end }}
  tls:
    secretName: {{ $.Values.name }}-certificate
{{- end }}