{{- if eq $.Values.service.enabled true }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.name }}-service
  annotations:
  {{- with $.Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ $.Values.name }}
  {{- if $.Values.service.extIP }}
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  type: LoadBalancer
  loadBalancerIP: {{ $.Values.service.extIP }}
  {{- end }}
  ports:
  {{- range $.Values.containers }}
  {{- range .ports }}
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
      name: {{ .name }}-tcp
    - protocol: UDP
      port: {{ .port }}
      targetPort: {{ .port }}
      name: {{ .name }}-udp
  {{- end }}
  {{- end }}
{{- end }}