apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestrr
  labels:
    app: requestrr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: requestrr
  template:
    metadata:
      labels:
        app: requestrr
    spec:
      containers:
      - name: requestrr
        image: lscr.io/linuxserver/requestrr:latest
        ports:
        - containerPort: 4545
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/London"