apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hashicorp-consul-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`consul.homelab.bowmans.site`)
      kind: Rule
      services:
      - name: hashicorp-consul-consul-server
        port: 8500
      middlewares:
      - name: private-ips-allow
        namespace: traefik
  tls:
    secretName: hashicorp-consul-certificate