apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-radarr
spec:
  secretName: ext-cert-radarr
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: radarr.bowmans.site
  dnsNames:
    - radarr.bowmans.site