apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homer-k8s-certificate
spec:
  secretName: homer-k8s-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: homer.homelab.bowmans.site
  dnsNames:
    - homer.homelab.bowmans.site