apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: homer-spc
spec:
  provider: vault
  parameters:
    vaultAddress: 'http://hashicorp-vault.hashicorp-vault:8200'
    roleName: 'main-role'
    objects: |
      - objectName: "BAZARR_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "BAZARR_API_KEY"
      - objectName: "OVERSEERR_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "OVERSEERR_API_KEY"
      - objectName: "RADARR_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "RADARR_API_KEY"
      - objectName: "SABNZBD_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "SABNZBD_API_KEY"
      - objectName: "SONARR_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "SONARR_API_KEY"
      - objectName: "TAUTULLI_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "TAUTULLI_API_KEY"
  secretObjects:
  - secretName: app-api-keys
    type: Opaque
    data:
    - key: BAZARR_API_KEY
      objectName: BAZARR_API_KEY
    - key: OVERSEERR_API_KEY
      objectName: OVERSEERR_API_KEY
    - key: RADARR_API_KEY
      objectName: RADARR_API_KEY
    - key: SABNZBD_API_KEY
      objectName: SABNZBD_API_KEY
    - key: SONARR_API_KEY
      objectName: SONARR_API_KEY
    - key: TAUTULLI_API_KEY
      objectName: TAUTULLI_API_KEY