authentik:
  secret_key: "TemporarySecretKey"
  error_reporting:
    enabled: true
  postgresql:
    password: "TemporaryPassword"

server:
  ingress:
    enabled: false

postgresql:
  enabled: true
  auth:
    password: "TemporaryPassword"