apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backups
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: '0 1 * * ?'
  groups:
  - default
  labels: {}
  name: Backups
  parameters: {}
  retain: 1
  task: backup