apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-tdarr
spec:
  secretName: ext-cert-tdarr
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: tdarr.homelab.bowmans.site
  dnsNames:
    - tdarr.homelab.bowmans.site