apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ext-ingress-route-tdarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tdarr.bowmans.site`)
      kind: Rule
      services:
      - name: ext-svc-tdarr
        port: 30028
      middlewares:
      - name: private-ips-allow
        namespace: traefik
  tls:
    secretName: ext-cert-tdarr