persistence:
  config:
    enabled: true
    mountPath: /www/assets
    retain: true
  test:
    enabled: true
    type: emptyDir
configMaps:
  config:
    enabled: true
    data:
      config.yml: |
        externalConfig: https://raw.githubusercontent.com/sam-bowman/homelab-cluster/main/argocd/utility/homer/config/config.yaml
