apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.10.20.50
    path: "/mnt/app-pool/apps/heimdall"
    readOnly: false