apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: my-test-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: my-test-external-secret
  data:
  - secretKey: foobar
    remoteRef:
      key: secret/APP_API_KEYS