apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tautulli-k8s-certificate
spec:
  secretName: tautulli-k8s-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: tautulli.homelab.bowmans.site
  dnsNames:
    - tautulli.homelab.bowmans.site