apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tautulli-k8s-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem