apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-certificate
spec:
  secretName: homepage-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: homepage.bowmans.site
  dnsNames:
    - homepage.bowmans.site