apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-api-keys
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: app-api-keys
  data:
  - secretKey: HOMEPAGE_VAR_ARGOCD_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: ARGOCD_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_BAZARR_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: BAZARR_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_HASS_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: HASS_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_OPNSENSE_PASSWORD
    remoteRef:
      key: secret/APP_API_KEYS
      property: OPNSENSE_PASSWORD
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: HOMEPAGE_VAR_OPNSENSE_USERNAME
    remoteRef:
      key: secret/APP_API_KEYS
      property: OPNSENSE_USERNAME
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_OVERSEERR_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: OVERSEERR_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_PLEX_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: PLEX_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_PTERODACTYL_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: PTERODACTYL_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_PVE_PASSWORD
    remoteRef:
      key: secret/APP_API_KEYS
      property: PVE_PASSWORD
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: HOMEPAGE_VAR_PVE_USERNAME
    remoteRef:
      key: secret/APP_API_KEYS
      property: PVE_USERNAME
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_RADARR_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: RADARR_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_READARR_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: READARR_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_SABNZBD_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: SABNZBD_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_SONARR_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: SONARR_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_TAUTULLI_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: TAUTULLI_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_TRUENAS_API_KEY
    remoteRef:
      key: secret/APP_API_KEYS
      property: TRUENAS_API_KEY
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

  - secretKey: HOMEPAGE_VAR_UNIFI_PASSWORD
    remoteRef:
      key: secret/APP_API_KEYS
      property: UNIFI_PASSWORD
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: HOMEPAGE_VAR_UNIFI_USERNAME
    remoteRef:
      key: secret/APP_API_KEYS
      property: UNIFI_USERNAME
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None