apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: homepage-spc
spec:
  provider: vault
  parameters:
    vaultAddress: 'http://hashicorp-vault.hashicorp-vault:8200'
    roleName: 'main-role'

    objects: |
      - objectName: "HOMEPAGE_VAR_ARGOCD_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "ARGOCD_API_KEY"

      - objectName: "HOMEPAGE_VAR_BAZARR_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "BAZARR_API_KEY"

      - objectName: "HOMEPAGE_VAR_HASS_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "HASS_API_KEY"

      - objectName: "HOMEPAGE_VAR_OPNSENSE_PASSWORD"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "OPNSENSE_PASSWORD"
      - objectName: "HOMEPAGE_VAR_OPNSENSE_USERNAME"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "OPNSENSE_USERNAME"

      - objectName: "HOMEPAGE_VAR_OVERSEERR_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "OVERSEERR_API_KEY"

      - objectName: "HOMEPAGE_VAR_PLEX_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "PLEX_API_KEY"

      - objectName: "HOMEPAGE_VAR_PTERODACTYL_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "PTERODACTYL_API_KEY"

      - objectName: "HOMEPAGE_VAR_PVE_PASSWORD"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "PVE_PASSWORD"
      - objectName: "HOMEPAGE_VAR_PVE_USERNAME"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "PVE_USERNAME"

      - objectName: "HOMEPAGE_VAR_RADARR_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "RADARR_API_KEY"

      - objectName: "HOMEPAGE_VAR_READARR_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "READARR_API_KEY"

      - objectName: "HOMEPAGE_VAR_SABNZBD_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "SABNZBD_API_KEY"

      - objectName: "HOMEPAGE_VAR_SONARR_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "SONARR_API_KEY"

      - objectName: "HOMEPAGE_VAR_TAUTULLI_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "TAUTULLI_API_KEY"

      - objectName: "HOMEPAGE_VAR_TRUENAS_API_KEY"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "TRUENAS_API_KEY"

      - objectName: "HOMEPAGE_VAR_UNIFI_PASSWORD"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "UNIFI_PASSWORD"
      - objectName: "HOMEPAGE_VAR_UNIFI_USERNAME"
        secretPath: "secret/data/APP_API_KEYS"
        secretKey: "UNIFI_USERNAME"

  secretObjects:
  - secretName: app-api-keys
    type: Opaque
    data:
      - key: "HOMEPAGE_VAR_ARGOCD_API_KEY"
        objectName: "HOMEPAGE_VAR_ARGOCD_API_KEY"

      - key: "HOMEPAGE_VAR_BAZARR_API_KEY"
        objectName: "HOMEPAGE_VAR_BAZARR_API_KEY"

      - key: "HOMEPAGE_VAR_HASS_API_KEY"
        objectName: "HOMEPAGE_VAR_HASS_API_KEY"

      - key: "HOMEPAGE_VAR_OPNSENSE_PASSWORD"
        objectName: "HOMEPAGE_VAR_OPNSENSE_PASSWORD"
      - key: "HOMEPAGE_VAR_OPNSENSE_USERNAME"
        objectName: "HOMEPAGE_VAR_OPNSENSE_USERNAME"

      - key: "HOMEPAGE_VAR_OVERSEERR_API_KEY"
        objectName: "HOMEPAGE_VAR_OVERSEERR_API_KEY"

      - key: "HOMEPAGE_VAR_PLEX_API_KEY"
        objectName: "HOMEPAGE_VAR_PLEX_API_KEY"

      - key: "HOMEPAGE_VAR_PTERODACTYL_API_KEY"
        objectName: "HOMEPAGE_VAR_PTERODACTYL_API_KEY"

      - key: "HOMEPAGE_VAR_PVE_PASSWORD"
        objectName: "HOMEPAGE_VAR_PVE_PASSWORD"
      - key: "HOMEPAGE_VAR_PVE_USERNAME"
        objectName: "HOMEPAGE_VAR_PVE_USERNAME"

      - key: "HOMEPAGE_VAR_RADARR_API_KEY"
        objectName: "HOMEPAGE_VAR_RADARR_API_KEY"

      - key: "HOMEPAGE_VAR_READARR_API_KEY"
        objectName: "HOMEPAGE_VAR_READARR_API_KEY"

      - key: "HOMEPAGE_VAR_SABNZBD_API_KEY"
        objectName: "HOMEPAGE_VAR_SABNZBD_API_KEY"

      - key: "HOMEPAGE_VAR_SONARR_API_KEY"
        objectName: "HOMEPAGE_VAR_SONARR_API_KEY"

      - key: "HOMEPAGE_VAR_TAUTULLI_API_KEY"
        objectName: "HOMEPAGE_VAR_TAUTULLI_API_KEY"

      - key: "HOMEPAGE_VAR_TRUENAS_API_KEY"
        objectName: "HOMEPAGE_VAR_TRUENAS_API_KEY"

      - key: "HOMEPAGE_VAR_UNIFI_PASSWORD"
        objectName: "HOMEPAGE_VAR_UNIFI_PASSWORD"
      - key: "HOMEPAGE_VAR_UNIFI_USERNAME"
        objectName: "HOMEPAGE_VAR_UNIFI_USERNAME"