apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ext-ingress-route-sonarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.bowmans.site`)
      kind: Rule
      services:
      - name: ext-svc-sonarr
        port: 8989
      middlewares:
        - name: kube-system-private-ips-allow@kubernetescrd
  tls:
    secretName: ext-cert-sonarr