apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 25.21.0
    helm:
      valueFiles:
      - $values/argocd/monitoring/prometheus/values/values.yaml
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    path: argocd/monitoring/prometheus
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true