apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: victoria-metrics
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.22.0
    helm:
      valueFiles:
      - $values/argocd/monitoring/victoria-metrics/values/values.yaml
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    path: argocd/monitoring/victoria-metrics
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true