apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: victoria-metrics
  namespace: argocd
spec:
  destination:
    namespace: victoria-metrics
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 2
  sources:
  - chart: victoria-metrics-k8s-stack
    helm:
      valueFiles:
      - $values/argocd/monitoring/victoria-metrics/values/values.yaml
    repoURL: https://victoriametrics.github.io/helm-charts/
    targetRevision: 0.25.16
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/monitoring/victoria-metrics
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
