apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 2
  sources:
  - chart: grafana
    helm:
      valueFiles:
      - $values/argocd/monitoring/grafana/values/values.yaml
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.5.1
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/monitoring/grafana
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
