apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana-alloy
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 0.2.0
    helm:
      valueFiles:
      - $values/argocd/monitoring/grafana-alloy/values/values.yaml
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    path: argocd/monitoring/grafana-alloy
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true