apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website-certificate
spec:
  secretName: website-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: bowmans.site
  dnsNames:
    - bowmans.site
    - www.bowmans.site