apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: website-homelab-certificate
spec:
  secretName: website-homelab-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: website.homelab.bowmans.site
  dnsNames:
    - website.homelab.bowmans.site