apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-certificate
spec:
  secretName: coder-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: coder-homelab.bowmans.site
  dnsNames:
    - coder-homelab.bowmans.site
    - "*.coder-homelab.bowmans.site"
