apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: coder-wildcard-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`{host:.*\.coder\.bowmans\.site}`)
      kind: Rule
      services:
      - name: coder
        port: 80
  tls:
    secretName: coder-certificate