apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: requestrr
  namespace: argocd
spec:
  destination:
    namespace: requestrr
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 2
  sources:
  - chart: requestrr
    helm:
      valueFiles:
      - $values/argocd/media/requestrr/values/values.yaml
    repoURL: tccr.io/truecharts
    targetRevision: 12.1.8
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/media/requestrr
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true