apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maintainerr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: maintainerr
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    path: argocd/media/maintainerr
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
  revisionHistoryLimit: 2