apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-sabnzbd
spec:
  secretName: ext-cert-sabnzbd
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: sabnzbd.bowmans.site
  dnsNames:
    - sabnzbd.bowmans.site