apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: gitea-spc
spec:
  provider: vault
  parameters:
    vaultAddress: 'http://hashicorp-vault.hashicorp-vault:8200'
    roleName: 'main-role'
    objects: |
      - objectName: "admin_account_username"
        secretPath: "secret/data/admin_account"
        secretKey: "username"
      - objectName: "admin_account_password"
        secretPath: "secret/data/admin_account"
        secretKey: "password"
  secretObjects:
  - secretName: admin-user-secret
    type: Opaque
    data:
    - key: username
      objectName: admin_account_username
    - key: password
      objectName: admin_account_password
    