apiVersion: v1
kind: Service
metadata:
  name: website-ext
  annotations:
    metallb.universe.tf/address-pool: metallb-pool-reserved
    metallb.universe.tf/ip-allocated-from-pool: metallb-pool-reserved
spec:
  type: LoadBalancer
  loadBalancerIP: 10.10.20.203
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app: website