apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
spec:
  secretName: argocd-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: argocd-homelab.bowmans.site
  dnsNames:
    - argocd-homelab.bowmans.site