apiVersion: v1
kind: Secret
metadata:
  name: github-sam-bowman-homelab-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/sam-bowman/homelab-cluster
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-grafana
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://grafana.github.io/helm-charts
  name: grafana
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-victoria-metrics
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://victoriametrics.github.io/helm-charts
  name: victoriametrics
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-kubeshop
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://kubeshop.github.io/helm-charts
  name: kubeshop
  type: helm
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-ghcr
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  url: ghcr.io
stringData:
  name: ghcr.io
  type: helm