apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-overseerr
spec:
  secretName: ext-cert-overseerr
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: overseerr.bowmans.site
  dnsNames:
    - overseerr.bowmans.site