apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: requestrr-k8s-certificate
spec:
  secretName: requestrr-k8s-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: requestrr.homelab.bowmans.site
  dnsNames:
    - requestrr.homelab.bowmans.site