apiVersion: apps/v1
kind: Deployment
metadata:
  name: requestrr-k8s-deployment
  labels:
    app: requestrr-k8s
spec:
  selector:
    matchLabels:
      app: requestrr-k8s
  template:
    metadata:
      labels:
        app: requestrr-k8s
    spec:
      containers:
      - name: requestrr-k8s
        image: thomst08/requestrr:latest
        ports:
        - containerPort: 4545
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        - name: config
          mountPath: "/root/config"
          readOnly: false
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 400m
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "requestrr-k8s-spc"
      - name: config
        persistentVolumeClaim:
          claimName: requestrr-k8s-pvc