apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: requestrr-k8s-vpa
spec:
  targetRef:
    name: requestrr-k8s-deployment
    kind: Deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: "300m"
        memory: "300Mi"
      controlledResources:
      - memory
      - cpu