apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-tautulli
spec:
  secretName: ext-cert-tautulli
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: tautulli.bowmans.site
  dnsNames:
    - tautulli.bowmans.site