apiVersion: v1
kind: Service
metadata:
  name: ext-svc-tautulli
spec:
  type: ExternalName
  externalName: truenas.bowmans.site
  ports:
    - port: 80
      targetPort: 8181
      protocol: TCP
      name: tautulli