apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hashicorp-vault-certificate
spec:
  secretName: hashicorp-vault-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: vault.bowmans.site
  dnsNames:
    - vault.bowmans.site