apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hashicorp-vault-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault-homelab.bowmans.site`)
      kind: Rule
      services:
      - name: hashicorp-vault
        port: 8200
  tls:
    secretName: hashicorp-vault-certificate