{
 "title": "Kubernetes / API server",
 "description": "Monitor API server metrics",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"controlplane-apiserver\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Control Plane Metrics \nThis dashboard is to be meant to visualize the Control plane metrics in AKS clusters with Azure Managed Prometheus. Read more in [our documentation](https://aka.ms/aks/controlplanemetrics)."
   }
  },
  {
   "title": "API Server - Health Status",
   "type": "stat",
   "description": "Indicates whether at least one instance of  API server is available ",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"controlplane-apiserver\", cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Inflight Requests",
   "type": "timeseries",
   "description": "Inflight request by the API server instance",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "sum by (instance)(max_over_time(apiserver_current_inflight_requests{job=\"controlplane-apiserver\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server HTTP Request Total",
   "type": "timeseries",
   "description": "Counter of apiserver requests across instances",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Tota number of requests to the API server"
    }
   ]
  },
  { "title": "Requests ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "API Server HTTP Request by code ",
   "type": "timeseries",
   "description": "API server requests broken down by the HTTP response code. Error code 429 is split into throttled and eviction",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (code) (\r\n\r\n  label_replace(\r\n\r\n      label_replace(   \r\n\r\n          label_join(\r\n\r\n                    rate(apiserver_request_total{cluster=\"$cluster\"}[$__rate_interval]), \r\n\r\n                    \"resource_sub_code\", \"_\", \"resource\", \"subresource\", \"code\"), # concat labels of interest\r\n\r\n          \"code\", \"429-eviction\", \"resource_sub_code\", \"pods_eviction_429\"  # replace eviction 429 with 429-eviction\r\n\r\n      ),\r\n\r\n      \"code\", \"429-throttled\", \"code\", \"429\"  # replace plain 429 with 429-throttled\r\n\r\n  )\r\n\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server  Total HTTP Request split by verb",
   "type": "timeseries",
   "description": "The total number of API  server requests broken down by the verb",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by (verb) (rate(apiserver_request_total{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "API server latency for LIST queries",
   "type": "timeseries",
   "description": "P95 API server Latency: Restricted to cluster and namespaces resource, also excludes WATCH operations. This query includes the webhook execution duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{job=\"controlplane-apiserver\", cluster=\"$cluster\", resource=~\"cluster|namespaces\", verb=\"list\", operation!=\"watch\"}[5m])) by (le))",
     "legendFormat": "P95 API server request duration in seconds"
    }
   ]
  },
  {
   "title": " API server latency SLI for LIST queries",
   "type": "timeseries",
   "description": "P95 API server latency not counting webhook duration and priority & fairness queue wait times. Restricted to cluster and namespaces resource, also excludes WATCH operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_sli_duration_seconds_bucket{job=\"controlplane-apiserver\", cluster=\"$cluster\", resource=~\"cluster|namespaces\", verb=\"list\", operation!=\"watch\"}[5m])) by (le))",
     "legendFormat": "P95 API server SLI duration in seconds"
    }
   ]
  },
  {
   "title": "API Server latency for NON-LIST queries",
   "type": "timeseries",
   "description": "P95 API server latency. Scope limited to resource and empty, excludes WATCH operations. This query includes the webhook execution duration",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{job=\"controlplane-apiserver\", cluster=\"$cluster\", verb!=\"list\", operation!=\"watch\", scope=~\"resource|^$\"}[5m])) by (le))",
     "legendFormat": "P95 API server request duration in seconds "
    }
   ]
  },
  {
   "title": " API Server latency for NON-LIST queries",
   "type": "timeseries",
   "description": "P95 API server latency not counting webhook duration and priority & fairness queue wait times. .Scope limited to resource and empty, excludes WATCH operations. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_sli_duration_seconds_bucket{job=\"controlplane-apiserver\", cluster=\"$cluster\", verb!=\"list\", operation!=\"watch\", scope=~\"resource|^$\"}[5m])) by (le))",
     "legendFormat": "P95 API server request SLI duration in seconds "
    }
   ]
  },
  {
   "title": "API server cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Server Cache List Fetched Objects by resource prefix",
     "type": "timeseries",
     "description": "Number of objects read from watch cache in the course of serving a LIST request",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(rate(apiserver_cache_list_fetched_objects_total{cluster=\"$cluster\",job=\"controlplane-apiserver\"}[$__rate_interval])) by (resource_prefix)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "API Server Cache List Returned Objects by resource_prefix",
     "type": "timeseries",
     "description": "Number of objects returned for a LIST request from watch cache",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "expr": "sum(rate(apiserver_cache_list_returned_objects_total{cluster=\"$cluster\",job=\"controlplane-apiserver\"}[$__rate_interval])) by (resource_prefix)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "API Server storage List Returned objects",
   "type": "timeseries",
   "description": "Number of objects returned for a LIST request from storage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_storage_list_returned_objects_total{cluster=\"$cluster\",job=\"controlplane-apiserver\"}[$__rate_interval])) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Server storage List Fetched objects",
   "type": "timeseries",
   "description": "Number of objects read from storage in the course of serving a LIST request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_storage_list_fetched_objects_total{cluster=\"$cluster\",job=\"controlplane-apiserver\"}[$__rate_interval])) by (resource)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Process start time for the API server",
   "type": "timeseries",
   "description": "Number of hours for which the API server has been running since the inception/restart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"controlplane-apiserver\", cluster=\"$cluster\"}/3600",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Flow Control Current Demand Seats by priority levels",
   "type": "timeseries",
   "description": "Time-weighted average, over last adjustment period, of demand_seats",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_demand_seats_average{cluster=\"$cluster\",job=\"controlplane-apiserver\"}) by (priority_level)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flow Control Current Limit Seats by priority levels",
   "type": "timeseries",
   "description": "Current derived number of execution seats available to each priority level",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_current_limit_seats{cluster=\"$cluster\",job=\"controlplane-apiserver\"}) by (priority_level)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}