{
 "title": "Kubernetes / ETCD",
 "description": "Monitor ETCD metrics",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(up{job=\"controlplane-apiserver\"}, cluster)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Control Plane Metrics \nThis dashboard is to be meant to visualize the Control plane metrics in AKS clusters with Azure Managed Prometheus. Read more in [our documentation](https://aka.ms/aks/controlplanemetrics)."
   }
  },
  {
   "title": "ETCD - Health Status",
   "type": "stat",
   "description": "Indicates whether at least one instance of  etcd is available ",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(up{job=\"controlplane-etcd\", cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "ETCD has leader",
   "type": "stat",
   "description": "Indicates if ETCD has a leader",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_has_leader{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "ETCD heartbeat send failures",
   "type": "stat",
   "description": "Max heartbeat send failures",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_heartbeat_send_failures_total{cluster='$cluster'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD Slow Apply total ",
   "type": "stat",
   "description": "Max heartbeat send failures",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_slow_apply_total{cluster='$cluster'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD Slow Read Indexes total ",
   "type": "stat",
   "description": "Max Slow Read indexes total",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(etcd_server_slow_read_indexes_total{cluster='$cluster'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage Utlilzation of ETCD database",
   "type": "graph",
   "description": "ETCD database utilization by instance ",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*etcd_mvcc_db_total_size_in_use_in_bytes{cluster='$cluster'} /etcd_mvcc_db_total_size_in_bytes{cluster='$cluster'} ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total  Client Requests",
   "type": "graph",
   "description": "Total client requests",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{cluster='$cluster'}[1m]))",
     "legendFormat": "Total client requests"
    }
   ]
  },
  {
   "title": "ETCD Network GRPC bytes",
   "type": "graph",
   "description": "The total number of bytes received/semt from grpc clients",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_network_client_grpc_received_bytes_total{cluster='$cluster'}[1m]))",
     "legendFormat": "Received bytes"
    },
    {
     "expr": "sum(rate(etcd_network_client_grpc_sent_bytes_total{cluster='$cluster'}[1m]))",
     "legendFormat": "Sent Bytes"
    }
   ]
  }
 ]
}