{
 "title": "Kubernetes / Networking / DNS (Workload)",
 "tags": [ "k8s:network-observability" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "Nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "query_result(label_replace(count by (destination) (hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}), \"ns\", \"$1\", \"destination\", \"(.*)\") or label_replace(count by (source) (hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}), \"ns\", \"$1\", \"source\", \"(.*)\") or label_replace(count by (destination) (hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}), \"ns\", \"$1\", \"destination\", \"(.*)\") or label_replace(count by (source) (hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}), \"ns\", \"$1\", \"source\", \"(.*)\"))"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "query_result(count by (workload) (label_replace(count by (destination) (hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/[a-z0-9]+$\"}), \"workload\", \"$1\", \"destination\", \"^$namespace/([a-z0-9]+)\")) or count by (workload) (label_replace(count by (destination) (hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/[a-z0-9]+-\"}), \"workload\", \"$1\", \"destination\", \"^$namespace/(.*)-[a-z0-9]+\")) or count by (workload) (label_replace(count by (source) (hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/[a-z0-9]+$\"}), \"workload\", \"$1\", \"source\", \"^$namespace/([a-z0-9]+)\")) or count by (workload) (label_replace(count by (source) (hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/[a-z0-9]+-\"}), \"workload\", \"$1\", \"source\", \"^$namespace/(.*)-[a-z0-9]+\")) or count by (workload) (label_replace(count by (destination) (hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/[a-z0-9]+$\"}), \"workload\", \"$1\", \"destination\", \"^$namespace/([a-z0-9]+)\")) or count by (workload) (label_replace(count by (destination) (hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/[a-z0-9]+-\"}), \"workload\", \"$1\", \"destination\", \"^$namespace/(.*)-[a-z0-9]+\")) or count by (workload) (label_replace(count by (source) (hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/[a-z0-9]+$\"}), \"workload\", \"$1\", \"source\", \"^$namespace/([a-z0-9]+)\")) or count by (workload) (label_replace(count by (source) (hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/[a-z0-9]+-\"}), \"workload\", \"$1\", \"source\", \"^$namespace/(.*)-[a-z0-9]+\")))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "***NOTE: requires Advanced Container Networking Services (standard offering) to be enabled. See [aka.ms/acns](https://aka.ms/acns) for more info.***"
   }
  },
  { "title": "Workload Snapshot ($workload)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "DNS Requests and Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "targets": [
    {
     "expr": "sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval]))\r\nor\r\nsum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval]))\r\nor\r\nsum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval]))",
     "legendFormat": "Responses"
    },
    {
     "expr": "clamp_min((\r\n    1 - (\r\n        sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])) / sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval]))\r\n    )\r\n) * 100 * (\r\n    (\r\n        sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval]))\r\n    ) > bool 0\r\n), 0)\r\nor\r\nclamp_min((\r\n    1 - (\r\n        sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])) / sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval]))\r\n    )\r\n) * 100 * (\r\n    (\r\n        sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval]))\r\n    ) > bool 0\r\n), 0)",
     "legendFormat": "Requests missing Response (%)"
    }
   ]
  },
  {
   "title": "DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "resp/s" } },
   "targets": [
    {
     "expr": "sum by (rcode, qtypes) (\r\n    rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"no error\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n    or\r\n    rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"no error\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n) > 0",
     "legendFormat": "{{rcode}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "DNS Errors by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "resp/s" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n    rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"no error\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n    or\r\n    rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"no error\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workload-Level ($workload)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "DNS Response IPs Returned",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "resp/s" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode=\"no error\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n  or\r\n  rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode=\"no error\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n) by (ips_returned) > 0",
     "legendFormat": "{{num_response}}"
    }
   ]
  },
  {
   "title": "DNS Missing Response by Query Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((\r\n    1 - (\r\n        sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])) by (qtypes)\r\n        / sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])) by (qtypes)\r\n    )\r\n) * 100 * (\r\n    (\r\n        sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])) by (qtypes)\r\n    ) > bool 0\r\n) > 0) # so that the legend always shows, do not filter > 0\r\nor\r\n((\r\n    1 - (\r\n        sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])) by (qtypes)\r\n        / sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])) by (qtypes)\r\n    )\r\n) * 100 * (\r\n    (\r\n        sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])) by (qtypes)\r\n    ) > bool 0\r\n) > 0) # so that the legend always shows, do not filter > 0",
     "legendFormat": "{{qtypes}}"
    }
   ]
  },
  {
   "title": "Top DNS Queries (Requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "topk(10, 60*sum (\r\n  rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n  or\r\n  rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n) by (query, qtypes))",
     "legendFormat": "{{query}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "Top DNS Queries (Responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "resp/min" } },
   "targets": [
    {
     "expr": "topk(10, sum (\r\n  60*(\r\n    rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n    or\r\n    rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n  )\r\n) by (query, qtypes))",
     "legendFormat": "{{query}} ({{qtypes}})"
    }
   ]
  },
  { "title": "Top Pods (for $workload)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Top Pods with DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "resp/min" } },
   "targets": [
    {
     "expr": "topk(10, 60*sum(\r\n  rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"No Error\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n) by (destination))\r\nor\r\ntopk(10, 60*sum(\r\n  rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"No Error\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n) by (source))",
     "legendFormat": "{{destination}}{{source}}"
    }
   ]
  },
  {
   "title": "Pods with the Most Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "topk(10, 60*sum(\r\n  rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n) by (source))\r\nor\r\ntopk(10, 60*sum(\r\n  rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n) by (destination))",
     "legendFormat": "{{destination}}"
    }
   ]
  }
 ]
}