{
 "title": "Kubernetes / Networking / Drops (Workload)",
 "tags": [ "k8s:network-observability" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info, cluster)"
    }
   },
   {
    "name": "Nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"},node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "query_result(label_replace(count by (destination) (hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\"}), \"ns\", \"$1\", \"destination\", \"(.*)\") or label_replace(count by (source) (hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\"}), \"ns\", \"$1\", \"source\", \"(.*)\"))"
    }
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "query_result(count by (workload) (label_replace(count by (destination) (hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/[a-z0-9]+$\"}), \"workload\", \"$1\", \"destination\", \"^$namespace/([a-z0-9]+)\")) or count by (workload) (label_replace(count by (destination) (hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/[a-z0-9]+-\"}), \"workload\", \"$1\", \"destination\", \"^$namespace/(.*)-[a-z0-9]+\")) or count by (workload) (label_replace(count by (source) (hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/[a-z0-9]+$\"}), \"workload\", \"$1\", \"source\", \"^$namespace/([a-z0-9]+)\")) or count by (workload) (label_replace(count by (source) (hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/[a-z0-9]+-\"}), \"workload\", \"$1\", \"source\", \"^$namespace/(.*)-[a-z0-9]+\")))"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "***NOTE: requires Advanced Container Networking Services (standard offering) to be enabled. See [aka.ms/acns](https://aka.ms/acns) for more info.***"
   }
  },
  { "title": "Workload Snapshot ($workload)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Pods with Outgoing Drops (past 10 minutes)",
   "type": "stat",
   "description": "Drops seen on the VM of the source Pod (a drop will appear for only one of \"incoming\" or \"outgoing\")",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count (\r\n  sum by (source) (\r\n    rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[10m])\r\n  ) > 0\r\n)",
     "legendFormat": "Pods with Outgoing Drops"
    }
   ]
  },
  {
   "title": "Max Outgoing Drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Max Outgoing Drops"
    }
   ]
  },
  {
   "title": "Min Outgoing Drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Min Outgoing Drops"
    }
   ]
  },
  {
   "title": "Pods with Incoming Drops (past 10 minutes)",
   "type": "stat",
   "description": "Drops seen on the VM of the destination Pod (a drop will appear for only one of \"incoming\" or \"outgoing\")",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count (\r\n  sum by (destination) (\r\n    rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[10m])\r\n  ) > 0\r\n)",
     "legendFormat": "Pods with Incoming Drops"
    }
   ]
  },
  {
   "title": "Max Incoming Drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Max Incoming Drops"
    }
   ]
  },
  {
   "title": "Min Incoming Drops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "round(sum (rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])), 0.01)",
     "legendFormat": "Min Incoming Drops"
    }
   ]
  },
  { "title": "Drops (for $workload)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Dropped Outgoing Traffic by Reason",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Dropped Incoming Traffic by Reason",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Heatmap of Outgoing Drops for Top Source Pods",
   "type": "heatmap",
   "description": "Drops seen on the VM of the source Pod (a drop will appear for only one of \"incoming\" or \"outgoing\").\n\nTypeError means there are no drops or no data",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, round(sum by (source) (\r\n  rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n), 0.01)) > 0",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Heatmap of Incoming Drops for Top Destination Pods",
   "type": "heatmap",
   "description": "Drops seen on the VM of the destination Pod (a drop will appear for only one of \"incoming\" or \"outgoing\").\n\nTypeError means there are no drops or no data",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, round(sum by (destination) (\r\n  rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n), 0.01)) > 0",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Stacked (Total) Outgoing Drops by Source Pod",
   "type": "timeseries",
   "description": "Drops seen on the VM of the source Pod (a drop will appear for only one of \"incoming\" or \"outgoing\")",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "round(\r\n  sum by (source) (\r\n    rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"^$namespace/$workload\"}[$__rate_interval])\r\n  ), 0.01\r\n)",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Stacked (Total) Incoming Drops by Destination Pod",
   "type": "timeseries",
   "description": "Drops seen on the VM of the destination Pod (a drop will appear for only one of \"incoming\" or \"outgoing\")",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "round(\r\n  sum by (destination) (\r\n    rate(hubble_drop_total{cluster=\"$cluster\", instance=~\"$Nodes\", destination=~\"^$namespace/$workload\"}[$__rate_interval])\r\n  ), 0.01\r\n)",
     "legendFormat": "{{destination}}"
    }
   ]
  }
 ]
}