{
 "title": "Kubernetes / Networking / DNS (Cluster)",
 "description": "One of the DNS dashboards for the Network Observability add-on for AKS (see [aka.ms/netobs](https://aka.ms/netobs)).",
 "tags": [ "k8s:network-observability" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "Nodes",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "***NOTE: requires Advanced Container Networking Services (standard offering) to be enabled. See [aka.ms/acns](https://aka.ms/acns) for more info.***"
   }
  },
  { "title": "Cluster Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "DNS Requests and Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "r/s" } },
   "targets": [
    {
     "expr": "sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))",
     "legendFormat": "Responses"
    },
    {
     "expr": "clamp_min((\r\n    1 - (\r\n        sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) / sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))\r\n    )\r\n) * 100 * (\r\n    (\r\n        sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval]))\r\n    ) > bool 0\r\n), 0) # so that the legend always shows, do not filter > 0",
     "legendFormat": "Requests missing Response (%)"
    }
   ]
  },
  {
   "title": "DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "resp/s" } },
   "targets": [
    {
     "expr": "sum by (rcode, qtypes) (\r\n    rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"no error\"}[$__rate_interval])\r\n) > 0",
     "legendFormat": "{{rcode}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "DNS Errors by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "resp/s" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n    rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"no error\"}[$__rate_interval])\r\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster-Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "DNS Response IPs Returned",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "resp/s" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode=\"no error\"}[$__rate_interval])) by (ips_returned) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Missing Response by Query Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n    1 - (\r\n        sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (qtypes)\r\n        / sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (qtypes)\r\n    )\r\n) * 100 * (\r\n    (\r\n        sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (qtypes)\r\n    ) > bool 0\r\n) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top DNS Queries (Requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "topk(10, 60 * sum (rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (query, qtypes))",
     "legendFormat": "{{query}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "Top DNS Queries (Responses)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "resp/min" } },
   "targets": [
    {
     "expr": "topk(10, 60 * sum (rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\"}[$__rate_interval])) by (query, qtypes))",
     "legendFormat": "{{query}} ({{qtypes}})"
    }
   ]
  },
  {
   "title": "DNS Response Table",
   "type": "table",
   "description": "Non-Cilium only",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "# label_replace(\r\n#   label_replace(\r\nsum by (query, query_type, response, return_code) (\r\n  60*rate(networkobservability_dns_response_count{cluster=\"$cluster\", instance=~\"$Nodes\", num_response!=\"0\", response!=\"\"}[$__range])\r\n) > 0\r\n# , \"return_code\", \"non-existent domain\", \"return_code\", \"nxdomain\"\r\n#   ), \"return_code\", \"success\", \"return_code\", \"noerror\"\r\n# )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top Pods (all namespaces)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Top Pods with DNS Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "resp/min" } },
   "targets": [
    {
     "expr": "topk(10, 60*sum(rate(hubble_dns_responses_total{cluster=\"$cluster\", instance=~\"$Nodes\", rcode!=\"No Error\", destination=~\"/\"}[$__rate_interval])) by (destination))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods with the Most Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "expr": "topk(10, 60*sum(rate(hubble_dns_queries_total{cluster=\"$cluster\", instance=~\"$Nodes\", source=~\"/\"}[$__rate_interval])) by (source))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}