apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-with-secret
  labels:
    app: deployment-with-secret
spec:
  selector:
    matchLabels:
      app: deployment-with-secret
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-skip-verify: "true"
        vault.hashicorp.com/agent-inject-secret-cloudflare: "secret/cloudflare"
        vault.hashicorp.com/agent-inject-template-cloudflare: |
          {{- with secret "secret/cloudflare" -}}
          {{ .Data.data.globalapikey }}
          {{- end }}
        vault.hashicorp.com/role: "main-role"
      labels:
        app: deployment-with-secret
    spec:
      serviceAccountName: test-objects
      containers:
      - name: busybox
        image: registry.k8s.io/e2e-test-images/busybox:1.29-4
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/sleep"
        - "10000"
        volumeMounts:
        - name: 'secrets'
          mountPath: '/mnt/secrets-store'
          readOnly: true
        env:
        - name: CLOUDFLAREGLOBALAPIKEY
          valueFrom:
            secretKeyRef:
              name: globalapikey
              key: globalapikey
      volumes:
        - name: secrets
          csi:
            driver: 'secrets-store.csi.k8s.io'
            readOnly: true
            volumeAttributes:
              secretProviderClass: 'test-secretproviderclass'