apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-readarr
spec:
  secretName: ext-cert-readarr
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: readarr.bowmans.site
  dnsNames:
    - readarr.bowmans.site