apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-syncthing
spec:
  secretName: ext-cert-syncthing
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: syncthing.bowmans.site
  dnsNames:
    - syncthing.bowmans.site