apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno-policies
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://kyverno.github.io/kyverno
    chart: kyverno-policies
    targetRevision: 3.2.1
    helm:
      valueFiles:
      - $values/argocd/utility/kyverno-policies/values/values.yaml
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    path: argocd/utility/kyverno-policies
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    - RespectIgnoreDifferences=true
ignoreDifferences:
  - group: kyverno.io
    kind: ClusterPolicy
    jqPathExpressions:
    - .spec.rules[] | select(.skipBackgroundRequests == true)