apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: kro
  namespace: argocd
spec:
  destination:
    namespace: kro
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 2
  sources:
  - chart: kro
    helm:
      valueFiles:
      - $values/argocd/utility/kro/values/values.yaml
    repoURL: ghcr.io/kro-run/kro
    targetRevision: 0.2.2
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/utility/kro
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
