apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: csi-secrets-store
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    chart: csi-secrets-store
    targetRevision: 1.4.3
    helm:
      valueFiles:
      - $values/argocd/utility/csi-secrets-store/values/values.yaml
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    path: argocd/utility/csi-secrets-store
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true