apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: csi-secrets-store
  namespace: argocd
spec:
  destination:
    namespace: csi-secrets-store
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: storage.k8s.io
    jqPathExpressions:
    - .spec.seLinuxMount
    kind: CSIDriver
  project: default
  revisionHistoryLimit: 2
  sources:
  - chart: secrets-store-csi-driver
    helm:
      valueFiles:
      - $values/argocd/utility/csi-secrets-store/values/values.yaml
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    targetRevision: 1.4.5
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/utility/csi-secrets-store
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    - RespectIgnoreDifferences=true
