apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: vpa
  namespace: argocd
spec:
  destination:
    namespace: vpa
    server: https://charts.fairwinds.com/stable
  project: default
  revisionHistoryLimit: 2
  sources:
  - chart: vpa
    helm:
      valueFiles:
      - $values/argocd/utility/vpa/values/values.yaml
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 4.5.0
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/utility/vpa
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
