apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: coder
  namespace: argocd
spec:
  destination:
    namespace: coder
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 2
  sources:
  - chart: coder
    helm:
      valueFiles:
      - $values/argocd/utility/coder/values/coder.yaml
    repoURL: https://helm.coder.com/v2
    targetRevision: 2.15.0
  - chart: postgresql
    helm:
      valueFiles:
      - $values/argocd/utility/coder/values/postgresql.yaml
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.5.36
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/utility/coder
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
