apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: keda
  namespace: argocd
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 2
  sources:
  - chart: keda
    helm:
      valueFiles:
      - $values/argocd/utility/keda/values/values.yaml
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.15.1
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/utility/keda
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
