apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-consul
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hashicorp-consul
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://helm.releases.hashicorp.com
    chart: consul
    targetRevision: 1.4.1
    helm:
      valueFiles:
      - $values/argocd/utility/consul/values/values.yaml
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
    ref: values
  - repoURL: https://github.com/sam-bowman/homelab-cluster
    path: argocd/utility/consul
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
      - .spec.volumeClaimTemplates[]
  revisionHistoryLimit: 2