apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: hashicorp-consul
  namespace: argocd
spec:
  destination:
    namespace: hashicorp-consul
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: apps
    jqPathExpressions:
    - .spec.volumeClaimTemplates[]
    kind: StatefulSet
  project: default
  revisionHistoryLimit: 2
  sources:
  - chart: consul
    helm:
      valueFiles:
      - $values/argocd/utility/consul/values/values.yaml
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 1.6.2
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/utility/consul
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    - RespectIgnoreDifferences=true
