apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-plex
spec:
  secretName: ext-cert-plex
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: plex.bowmans.site
  dnsNames:
    - plex.bowmans.site