apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ext-ingress-route-plex
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.bowmans.site`)
      kind: Rule
      services:
      - name: ext-svc-plex
        port: 32400
      middlewares:
      - name: private-ips-allow
        namespace: traefik
  tls:
    secretName: ext-cert-plex