apiVersion: v1
kind: Service
metadata:
  name: ext-svc-plex
spec:
  type: ExternalName
  externalName: truenas.bowmans.site
  ports:
    - port: 80
      targetPort: 32400
      protocol: TCP
      name: plex