apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: maintainerr-certificate
spec:
  secretName: maintainerr-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: maintainerr.homelab.bowmans.site
  dnsNames:
    - maintainerr.homelab.bowmans.site