apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: maintainerr-keda
spec:
  scaleTargetRef:
    name: maintainerr-deployment
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "80"