apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: cert-manager-spc
spec:
  provider: vault
  parameters:
    vaultAddress: 'http://hashicorp-vault.hashicorp-vault:8200'
    roleName: 'main-role'
    objects: |
      - objectName: "cloudflareglobalapikey"
        secretPath: "secret/data/cloudflare"
        secretKey: "globalapikey"
  secretObjects:
  - secretName: cloudflare-api-key-secret
    type: Opaque
    data:
    - key: api-key
      objectName: cloudflareglobalapikey
    