apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer-letsencrypt
spec:
  acme:
    email: bowmans9613@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-letsencrypt-secret
    solvers:
    - dns01:
        cloudflare:
          email: bowmans9613@gmail.com
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key