apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: overseerr-k8s-certificate
spec:
  secretName: overseerr-k8s-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: overseerr.homelab.bowmans.site
  dnsNames:
    - overseerr.homelab.bowmans.site