apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: overseerr-k8s-vpa-memory
spec:
  targetRef:
    name: overseerr-k8s-deployment
    kind: Deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources:
      - memory
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: overseerr-k8s-vpa-cpu
spec:
  targetRef:
    name: overseerr-k8s-deployment
    kind: Deployment
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      controlledResources:
      - cpu