crds:
  create: false
alloy:
  configMap:
    create: false
    name: grafana-alloy-config
    key: config.alloy
  enableReporting: false
  extraPorts:
  - name: grpc-otlp
    targetPort: 4137
    port: 4137
    protocol: TCP
  - name: http-otlp
    targetPort: 4138
    port: 4138
    protocol: TCP