apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-bazarr
spec:
  secretName: ext-cert-bazarr
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: bazarr.bowmans.site
  dnsNames:
    - bazarr.bowmans.site