apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ext-ingress-route-bazarr
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bazarr.bowmans.site`)
      kind: Rule
      services:
      - name: ext-svc-bazarr
        port: 30046
  tls:
    secretName: ext-cert-bazarr