apiVersion: apps/v1
kind: Deployment
metadata:
  name: doplarr-deployment
spec:
  selector:
    matchLabels:
      app: doplarr
  template:
    metadata:
      labels:
        app: doplarr
    spec:
      containers:
      - name: doplarr
        image: lscr.io/linuxserver/doplarr:latest
        env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        - name: TZ
          value: 'Europe/London'
        - name: OVERSEERR__URL
          value: 'https://overseerr.bowmans.site:443'
        - name: OVERSEERR__DEFAULT_ID
          value: '12'
        - name: DISCORD__TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: discord_token
        - name: OVERSEERR__API
          valueFrom:
            secretKeyRef:
              name: overseerr-api-key
              key: overseerr_api_key
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        - name: config
          mountPath: "/config"
        resources:
          limits:
            cpu: 250m
          requests:
            cpu: 200m
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "doplarr-spc"
      - name: config
        persistentVolumeClaim:
          claimName: doplarr-pvc