apiVersion: v1
kind: PersistentVolume
metadata:
  name: doplarr-pv
spec:
  storageClassName: ""
  claimRef:
    name: doplarr-pvc
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: doplarr-sc