apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doplarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem