kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: doplarr-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: doplarr-sc
  reclaimPolicy: Retain