apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sonarr-certificate
spec:
  secretName: sonarr-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: sonarr.homelab.bowmans.site
  dnsNames:
    - sonarr.homelab.bowmans.site