K3S_MASTER:
  hosts:
    K3SCLUSTER01: #10.10.20.60: #
K3S_NODES:
  hosts:
    K3SCLUSTER02: #10.10.20.61: #
    K3SCLUSTER03: #10.10.20.62: #
    K3SCLUSTER04: #10.10.20.62: #
K3S_CLUSTER:
  children:
    K3S_MASTER:
    K3S_NODES:
  vars:
    ansible_user: k3s_cluster_admin
    ansible_ssh_private_key_file: ../.ssh/id