- name: "01 - INITIAL CONFIGURATION - K3S_CLUSTER"
  hosts: K3S_CLUSTER
  vars:
    cmdline_add:
    - cgroup_enable=memory
    - cgroup_memory=1
  tasks:
  - name: "-- Update & Upgrade nodes --"
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: "-- Install Git-All --"
    become: true
    apt:
      name: git-all
      state: present

  - name: "-- Install Python Pip--"
    become: true
    apt:
      name: python3-pip
      state: present

  - name: "-- Install PipX --"
    become: true
    apt:
      name: pipx
      state: present

  - name: "-- Configure PipX --"
    command: pipx ensurepath

  - name: "-- Install open-iscsi --"
    become: true
    apt:
      name: open-iscsi
      state: present

  - name: "-- Enable service iscsid --"
    ansible.builtin.systemd_service:
      name: httpd
      enabled: true

  - name: "-- Start service iscsid --"
    ansible.builtin.systemd_service:
      name: httpd
      state: started
  
  - name: "-- Install DNSUtils --"
    become: true
    apt:
      name: dnsutils
      state: present

  - name: "-- Install K8S pip module --"
    become: true
    apt:
      name: python3-kubernetes
      state: present
    
  - name: "-- Install JsonPatch pip module --"
    become: true
    apt:
      name: python3-jsonpatch
      state: present
    
  - name: "-- Create repos directory --"
    file:
      path: "{{ ansible_env.HOME }}/repos"
      state: directory
      mode: '0755'

  - name: "-- Clone homelab-cluster repo --"
    git:
      repo: https://github.com/sam-bowman/homelab-cluster.git
      dest: "{{ ansible_env.HOME }}/repos/homelab-cluster"
      clone: yes
      update: yes

  - name: "-- Enable cgroups on cluster --"
    become: true
    lineinfile:
      path: /boot/firmware/cmdline.txt
      regexp: '^(?!.*?{{ item }})(.*)$'
      line: '\1 {{ item }}'
      backrefs: true
    loop: "{{ cmdline_add }}"

  - name: "-- Mount network share - smb --"
    become: true
    ansible.posix.mount:
      src: truenas:/mnt/pool/smb
      path: /mnt/nas_smb
      opts: rw,sync,hard
      state: mounted
      fstype: nfs

  - name: "-- Mount network share - tftp --"
    become: true
    ansible.posix.mount:
      src: truenas:/mnt/pool/tftp
      path: /mnt/nas_tftp
      opts: rw,sync,hard
      state: mounted
      fstype: nfs

  - name: "-- Mount network share - app_configs --"
    become: true
    ansible.posix.mount:
      src: truenas:/mnt/app-pool/apps
      path: /mnt/nas_app_configs
      opts: rw,sync,hard
      state: mounted
      fstype: nfs

  - name: "-- Mount network share - media --"
    become: true
    ansible.posix.mount:
      src: truenas:/mnt/pool/media
      path: /mnt/nas_media
      opts: rw,sync,hard
      state: mounted
      fstype: nfs
      