- name: Initial Configuration
  hosts: K3S_CLUSTER
  vars:
    cmdline_add:
    - cgroup_enable=memory
    - cgroup_memory=1
  tasks:
    - name: Update & Upgrade
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
    - name: Install GIT
      become: true
      apt:
        name: git-all
        state: present
    - name: Install pip
      become: true
      apt:
        name: python3-pip
        state: present
    - name: Install PIPX
      become: true
      apt:
        name: pipx
        state: present
    - name: Install DNSUtils
      become: true
      apt:
        name: dnsutils
        state: present
    - name: Configure PIPX Path
      command: pipx ensurepath
      run_once: true
    - name: Create Repo Directory
      file:
        path: ~/repos
        state: directory
        mode: '0755'
    - name: Clone homelab-cluster repo
      git:
        repo: https://github.com/sam-bowman/homelab-cluster.git
        dest: ~/repos/homelab-cluster
        clone: yes
        update: yes
    - name: Enable cgroups on cluster
      become: true
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: '^(?!.*?{{ item }})(.*)$'
        line: '\1 {{ item }}'
        backrefs: true
      loop: "{{ cmdline_add }}"
    - name: Reboot the cluster
      become: true
      reboot: