- name: BaseApps
  hosts: K3S_MASTER
  environment:
    K8S_AUTH_KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
    KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  tasks:
  - name: install kubernetes pip module
    become: true
    apt:
      name: python3-kubernetes
      state: present
  - name: install jsonpatch pip module
    become: true
    apt:
      name: python3-jsonpatch
      state: present
  - name: Download metallb manifest to the cluster.
    become: true
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/metallb/metallb/v0.14.3/config/manifests/metallb-native.yaml
      dest: ~/metallb.yaml
      mode: '0664'
  - name: Apply metallb manifest to the cluster.
    become: true
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      src: ~/metallb.yaml
  - name: Define metallb ip range - autoassigned
    become: true
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      definition:
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: metallb-pool-auto
          namespace: metallb-system
        spec:
          addresses:
          - 10.10.20.101-10.10.20.200
          avoidBuggyIPs: true
          autoAssign: true
  - name: Define metallb ip range - reserved
    become: true
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      definition:
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: metallb-pool-reserved
          namespace: metallb-system
        spec:
          addresses:
          - 10.10.20.201-10.10.20.220
          avoidBuggyIPs: true
          autoAssign: false
  - name: Enable k8s_external
    become: true
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: patched
      definition:
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: coredns
          namespace: kube-system
        data:
          Corefile: |
            .:53 {
                errors
                health
                ready
                kubernetes cluster.local in-addr.arpa ip6.arpa {
                  pods insecure
                  fallthrough in-addr.arpa ip6.arpa
                }
                k8s_external k8s.bowmans.site
                hosts /etc/coredns/NodeHosts {
                  ttl 60
                  reload 15s
                  fallthrough
                }
                prometheus :9153
                forward . /etc/resolv.conf
                cache 30
                loop
                reload
                loadbalance
                import /etc/coredns/custom/*.override
            }
            import /etc/coredns/custom/*.server
  - name: Define metallb l2 advertisement
    become: true
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      definition:
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: metallb-l2ad
          namespace: metallb-system
  - name: Create a argocd namespace
    become: true
    kubernetes.core.k8s:
      name: argocd
      api_version: v1
      kind: Namespace
      state: present
  - name: Download argocd manifest to the cluster.
    become: true
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      dest: ~/argocd.yaml
      mode: '0664'
  - name: Apply argocd manifest to the cluster.
    become: true
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/kube-config
      state: present
      src: ~/argocd.yaml
      namespace: argocd
  - name: Define coredns service for ext resolution UDP
    become: true
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: ext-dns-udp
          namespace: kube-system
          annotations:
            metallb.universe.tf/allow-shared-ip: "DNS"
            metallb.universe.tf/address-pool: metallb-pool-reserved
        spec:
          type: LoadBalancer
          loadBalancerIP: 10.10.20.201
          ports:
          - port: 53
            targetPort: 53
            protocol: UDP
          selector:
            k8s-app: kube-dns
  - name: Define coredns service for ext resolution TCP
    become: true
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: ext-dns-tcp
          namespace: kube-system
          annotations:
            metallb.universe.tf/allow-shared-ip: "DNS"
            metallb.universe.tf/address-pool: metallb-pool-reserved
        spec:
          type: LoadBalancer
          loadBalancerIP: 10.10.20.201
          ports:
          - port: 53
            targetPort: 53
            protocol: TCP
          selector:
            k8s-app: kube-dns
  - name: Patch argocd-server service to make it accessible
    become: true
    command: "kubectl patch svc argocd-server -n argocd -p '{\"spec\": {\"type\": \"LoadBalancer\"}}'"
  - name: bootstrap argocd apps
    become: true
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/kube-config
      state: present
      definition:
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: argocd-bootstrap
          namespace: argocd
          finalizers:
          - resources-finalizer.argocd.argoproj.io
        spec:
          destination:
            namespace: argocd
            server: https://kubernetes.default.svc
          project: default
          source:
            path: argocd
            repoURL: https://github.com/sam-bowman/homelab-cluster
            targetRevision: HEAD
  - name: Get argocd admin password
    become: true
    shell: "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath=\"{.data.password}\" | base64 -d"
    register: argocd_admin_pass
  - name: output argocd admin pass
    debug:
      msg: "{{ argocd_admin_pass.stdout }}"
    