MASTER:
  hosts:
    master_01:
      ansible_host: K3S_CLUSTER_01

NODES:
  hosts:
    node_01:
      ansible_host: K3S_CLUSTER_02

K3S_CLUSTER:
  children:
    MASTER:
    NODES:
  vars:
    ansible_user: k3s_cluster_admin

