apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: private-ips-allow
  namespace: kube-system
spec:
  ipAllowList:
    sourceRange:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 127.0.0.1