apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: traefik
    meta.helm.sh/release-namespace: kube-system
    metallb.universe.tf/ip-allocated-from-pool: metallb-pool-auto
  creationTimestamp: "2024-02-02T18:10:48Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-25.0.2_up25.0.0
  name: traefik
  namespace: kube-system
  resourceVersion: "46630"
  uid: 1525d271-8334-427a-b3f1-66944a4248c0
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.7.219
  clusterIPs:
  - 10.43.7.219
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: web
    nodePort: 32467
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    nodePort: 31155
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: traefik-kube-system
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.10.20.101