# /var/lib/rancher/k3s/server/manifests/traefik-helmchartconfig.yaml
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      enabled: true
      replicas: 3
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        allowExternalNameServices: true