apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heimdall-certificate
spec:
  secretName: heimdall-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: heimdall.homelab.bowmans.site
  dnsNames:
    - heimdall.homelab.bowmans.site