apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  labels:
    app: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      volumes:
      - name: heimdall-config
        persistentVolumeClaim:
          claimName: heimdall-config-claim
      containers:
      - image: lscr.io/linuxserver/heimdall:latest
        name: heimdall
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/config"
          name: heimdall-config