apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/nas_app_configs/k8s/heimdall"