apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: netbox
  namespace: argocd
spec:
  destination:
    namespace: netbox
    server: https://kubernetes.default.svc
  revisionHistoryLimit: 2
  project: default
  sources:
  - chart: netbox
    helm:
      valueFiles:
      - $values/argocd/network/netbox/values/values.yaml
    repoURL: ghcr.io/netbox-community/netbox-chart
    targetRevision: '5.0.0-beta.94'
  - ref: values
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  - path: argocd/network/netbox
    repoURL: https://github.com/sam-bowman/homelab-cluster
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - PruneLast=true
    - RespectIgnoreDifferences=true
