apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tdarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tdarr
    server: https://kubernetes.default.svc
  project: default
  sources:
    - helm:
        values: |
          name: tdarr
          port: 30028
          annotations:
            gethomepage.dev/href: "https://tdarr.bowmans.site/"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/description: Tdarr
            gethomepage.dev/group: Media
            gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/tdarr.png"
            gethomepage.dev/app: tdarr
            gethomepage.dev/name: Tdarr
            gethomepage.dev/widget.type: "tdarr"
            gethomepage.dev/widget.url: "https://tdarr.bowmans.site/"
            gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_TDARR_API_KEY}}"
            gethomepage.dev/pod-selector: "app.kubernetes.io/name=traefik"
      repoURL: https://github.com/sam-bowman/homelab-cluster.git
      path: charts/external-services
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  revisionHistoryLimit: 2