apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: radarr
    server: https://kubernetes.default.svc
  project: default
  sources:
    - helm:
        values: |
          name: radarr
          port: 30025
          annotations:
            gethomepage.dev/href: "https://radarr.bowmans.site/"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/description: Radarr
            gethomepage.dev/group: Media
            gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/radarr.png"
            gethomepage.dev/app: radarr
            gethomepage.dev/name: Radarr
            gethomepage.dev/widget.type: "radarr"
            gethomepage.dev/widget.url: "https://radarr.bowmans.site/"
            gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_RADARR_API_KEY}}"
            gethomepage.dev/namespace: kube-system
            gethomepage.dev/pod-selector: "app.kubernetes.io/name=traefik"
      repoURL: https://github.com/sam-bowman/homelab-cluster.git
      path: charts/external-services
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  revisionHistoryLimit: 2