apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: titlecardmaker
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: titlecardmaker
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: external-services
      helm:
        values: |
          name: titlecardmaker
          port: 34242
      repoURL: https://github.com/sam-bowman/homelab-cluster
      targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  revisionHistoryLimit: 2