apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sabnzbd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - helm:
        values: |
          name: sabnzbd
          port: 30055
          annotations:
            gethomepage.dev/href: "https://sabnzbd.bowmans.site/"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/description: SABnzbd
            gethomepage.dev/group: Media
            gethomepage.dev/icon: "https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/sabnzbd.png"
            gethomepage.dev/app: sabnzbd
            gethomepage.dev/name: SABnzbd
            gethomepage.dev/widget.type: "sabnzbd"
            gethomepage.dev/widget.url: "https://sabnzbd.bowmans.site/"
            gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_SABNZBD_API_KEY}}"
            gethomepage.dev/pod-selector: ""
      repoURL: https://github.com/sam-bowman/homelab-cluster.git
      path: charts/external-services
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  revisionHistoryLimit: 2