apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fossorial-pangolin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: zero
    server: https://kubernetes.default.svc
  project: default
  sources:
    - helm:
        values: |
          name: pangolin
          port: 443
          externalName: ubuntu-vps.bowmans.site
      repoURL: https://github.com/sam-bowman/homelab-cluster.git
      path: charts/external-services
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
  revisionHistoryLimit: 2