apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-certificate
spec:
  secretName: grafana-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: grafana.homelab.bowmans.site
  dnsNames:
    - grafana.homelab.bowmans.site