apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 0m
      memory: 0Mi
    max:
      cpu: 10000mi
      memory: 10Gi
    min:
      cpu: 0m
      memory: 0Mi
    type: Container