apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: gafana-spc
spec:
  provider: vault
  parameters:
    vaultAddress: 'http://hashicorp-vault.hashicorp-vault:8200'
    roleName: 'main-role'
    objects: |
      - objectName: "github_oauth_client_id"
        secretPath: "secret/data/github_oauth"
        secretKey: "client_id"
      - objectName: "github_oauth_client_secret"
        secretPath: "secret/data/github_oauth"
        secretKey: "client_secret"
  secretObjects:
  - secretName: github_oauth
    type: Opaque
    data:
    - key: client_id
      objectName: github_oauth_client_id
    - key: client_secret
      objectName: github_oauth_client_secret
    