apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ext-cert-airdcpp
spec:
  secretName: ext-cert-airdcpp
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: airdcpp.bowmans.site
  dnsNames:
    - airdcpp.bowmans.site