apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: unifi-certificate
spec:
  secretName: unifi-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: unifi-homelab.bowmans.site
  dnsNames:
    - unifi-homelab.bowmans.site