apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.homelab.bowmans.site`)
      kind: Rule
      services:
      - name: unifi
        port: 8443
        scheme: https
        serversTransport: unifi
      middlewares:
        - name: kube-system-private-ips-allow@kubernetescrd
  tls:
    secretName: unifi-certificate