apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi-ingress-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.bowmans.site`)
      kind: Rule
      services:
      - name: unifi
        port: 8443
        scheme: https
        serversTransport: unifi
  tls:
    secretName: unifi-certificate