apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
  volumeMode: Filesystem