apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-certificate
spec:
  secretName: radarr-certificate
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer-letsencrypt
  commonName: radarr.homelab.bowmans.site
  dnsNames:
    - radarr.homelab.bowmans.site