name: 'TERRAFORM - FIREWALL CONFIGURATION'

on:
  push:
    paths:
    - fw-config/**
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  OPNSENSE_API_KEY: {{ secrets.OPNSENSE_API_KEY }}
  OPNSENSE_API_SECRET: {{ secrets.OPNSENSE_API_SECRET }}
  OPNSENSE_URI: {{ secrets.OPNSENSE_URI }}

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: [self-hosted, linux, ARM64]
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: fw-config
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
